name: Publish Package to npm
on:
  push:
    branches: 
     - cra-template-gitlanding
jobs:
  test_template: 
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: node
       uses: actions/setup-node@v3
       with: 
          node-version: '16.x'
     - name: test-template
       run: | 
        cd ../
        mv gitlanding/ cra-template-gitlanding
        yarn create react-app test --template file:./cra-template-gitlanding
        cd test
        yarn build
        cd ../
        rm -rf test
        mv cra-template-gitlanding/ gitlanding

  check_if_version_upgraded:
    name: Check if version upgraded
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test_template
    outputs:
     from_version: ${{ steps.step1.outputs.from_version }}
     to_version: ${{ steps.step1.outputs.to_version }}
     is_upgraded_version: ${{steps.step1.outputs.is_upgraded_version }}
    steps: 
        - uses: garronej/github_actions_toolkit@v2.2
          id: step1
          with:
            action_name: is_package_json_version_upgraded


  update_changelog:
    runs-on: ubuntu-latest
    needs: check_if_version_upgraded
    if: needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
    steps:
    - uses: garronej/github_actions_toolkit@v2.2
      with:
        action_name: update_changelog
        branch: ${{ github.ref }}
        commit_author_email: ts_ci@github.com

  publish_to_npm:
    runs-on: ubuntu-latest
    needs: check_if_version_upgraded
    if: needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: node
       uses: actions/setup-node@v3
       with: 
          node-version: '16.x'
     - name: publish
       run: npm publish
       env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}