name: Publish Package to npm
on:
  push:
    branches: 
     - cra-template-gitlanding
jobs:
  #test_template: 
  #  runs-on: ubuntu-latest
  #  steps:
  #   - name: checkout
  #     uses: actions/checkout@v3
  #   - name: node
  #     uses: actions/setup-node@v3
  #     with: 
  #        node-version: '16.x'
  #   - name: test-template
  #     run: | 
  #      cd ../
  #      mv gitlanding/ cra-template-gitlanding
  #      yarn create react-app test --template file:./cra-template-gitlanding
  #      cd test
  #      yarn build
  #      cd ../
  #      rm -rf test
  #      mv cra-template-gitlanding/ gitlanding


  #check_if_version_upgraded:
  #  name: check if version upgraded
  #  if: github.event_name == 'push'
  #  runs-on: ubuntu-latest
  #  needs: test_template
  #  outputs:
  #    is_upgraded: ${{ steps.step1.outputs.is_upgraded }}
  #  steps:
  #    - uses: thieryw/check-version-upgrade@v1.0.2
  #      id: step1


  publish_to_npm:
    runs-on: ubuntu-latest
    #needs: test_template
    #if: needs.check_if_version_upgraded.outputs.is_upgraded == 'true'
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: node
       uses: actions/setup-node@v3
       with: 
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
     - name: publish
       run: npm publish
       env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}